name: vms
description: "CRCB volunteer management system."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.2.0-210.3.beta <4.0.0"

dependencies:
  backstreets_widgets: ^0.8.0
  cupertino_icons: ^1.0.2
  drift: ^2.13.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  path: ^1.8.3
  path_provider: ^2.1.1
  sqlite3_flutter_libs: ^0.5.18

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
